# SecretStore defines HOW to connect to the external secret provider (AWS Secrets Manager).
# It uses the ServiceAccount (IRSA) for authentication — no static credentials needed.
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: landmark
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
