apiVersion: v1
kind: Service
metadata:
  name: landmark-sa-service
  namespace: landmark
spec:
  type: LoadBalancer
  selector:
    app: landmark-sa-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
